'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AppMainPage

          '''<summary>
          '''form1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

          '''<summary>
          '''Image3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image

          '''<summary>
          '''Image2 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

          '''<summary>
          '''ImageButton12 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ImageButton12 As Global.System.Web.UI.WebControls.ImageButton

          '''<summary>
          '''Label6 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''txtLogonID control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtLogonID As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtLogonName control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtLogonName As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''btnLogout control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''mainpage control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents mainpage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''mainmenu control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents mainmenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''btnAdmin control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnAdmin As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMastMain control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMastMain As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnOper control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnOper As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnReport control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnReport As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnImpSAP control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnImpSAP As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnExpSAP control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnExpSAP As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Main control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Main As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Image4 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

          '''<summary>
          '''AdminFunc control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents AdminFunc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnAFUserAdmin control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnAFUserAdmin As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''OperFunc control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents OperFunc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label7 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnOFLotMgt control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnOFLotMgt As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnPartAdj control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnPartAdj As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnOFRework control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnOFRework As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnOFScrap control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnOFScrap As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnOFPrintTag control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnOFPrintTag As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnOFTraceAmend control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnOFTraceAmend As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''ReportFunc control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ReportFunc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label2 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnRFLineState control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFLineState As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnRFSerialOpen control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFSerialOpen As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnRFSerialHist control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFSerialHist As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnRFSerialSkip control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFSerialSkip As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnRFPartCons control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFPartCons As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnRFLotTrace control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFLotTrace As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnRFMotDock control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFMotDock As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnRFPartBal control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFPartBal As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnRFWorkerLog control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFWorkerLog As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnRFManuLotHistory control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFManuLotHistory As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnRFPartScrap control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnRFPartScrap As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''ImportSAP control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ImportSAP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnImpMaterialMaster control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnImpMaterialMaster As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnImpProdOrder control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnImpProdOrder As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnImpProdOrderComp control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnImpProdOrderComp As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnImpVendUOM control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnImpVendUOM As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''ExportSAP control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ExportSAP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label4 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnExpWorkResult control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnExpWorkResult As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnExpPartConsumption control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnExpPartConsumption As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnExpScrapInfo control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnExpScrapInfo As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''MastMaint control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents MastMaint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label5 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnMMLine control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMLine As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMStdUOM control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMStdUOM As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMShift control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMShift As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMProdCapa control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMProdCapa As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMProcess control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMProcess As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMProcess3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMProcess3 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMCompCode control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMCompCode As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMPlantCode control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMPlantCode As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMStep control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMStep As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMEquip control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMEquip As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMStepEquip control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMStepEquip As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''BtnMMTraceMast control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents BtnMMTraceMast As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMConspStep control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMConspStep As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMReason control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMReason As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMMWorkerReg control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMMWorkerReg As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''hflogonid control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents hflogonid As Global.System.Web.UI.WebControls.HiddenField

          '''<summary>
          '''hfSelItem control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents hfSelItem As Global.System.Web.UI.WebControls.HiddenField
End Class
