'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LotMaint

          '''<summary>
          '''form1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

          '''<summary>
          '''formheader control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formheader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Image1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

          '''<summary>
          '''formtitle control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formtitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''frmtitle control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents frmtitle As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''formbody control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formbody As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''formcontent control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formcontent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''formdetail control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formdetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label2 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label4 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label5 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label6 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label8 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label9 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label10 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label11 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label7 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label12 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label14 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label14 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label13 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''txtMfgLotNo control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtMfgLotNo As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtModelNo control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtModelNo As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtProdSchQty control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtProdSchQty As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtPassQty control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtPassQty As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''NGQty control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents NGQty As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtProcess control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtProcess As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtWorkSt control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtWorkSt As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtPartCon control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtPartCon As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtAbPassSkip control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtAbPassSkip As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtAbPassNG control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtAbPassNG As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtRem control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtRem As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''TextBox1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''TextBox8 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents TextBox8 As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtMAMMLot control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtMAMMLot As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''btnStartLot control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnStartLot As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnSuspendLot control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnSuspendLot As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnCloseLot control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnCloseLot As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnExit control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnExit As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''LoginUser control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents LoginUser As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Version control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Version As Global.System.Web.UI.WebControls.Label
End Class
