'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LotMainSel

          '''<summary>
          '''form1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

          '''<summary>
          '''formheader control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formheader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Image1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

          '''<summary>
          '''formtitle control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formtitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''frmtitle control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents frmtitle As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''ImageButton3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ImageButton3 As Global.System.Web.UI.WebControls.ImageButton

          '''<summary>
          '''formbody control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formbody As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''formcontent control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formcontent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label2 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label4 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label5 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''gvContent control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents gvContent As Global.System.Web.UI.WebControls.GridView

          '''<summary>
          '''ddlLineID control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ddlLineID As Global.System.Web.UI.WebControls.DropDownList

          '''<summary>
          '''SDALineID control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents SDALineID As Global.System.Web.UI.WebControls.SqlDataSource

          '''<summary>
          '''ddlProcFlowID control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ddlProcFlowID As Global.System.Web.UI.WebControls.DropDownList

          '''<summary>
          '''SDAProcFlowID control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents SDAProcFlowID As Global.System.Web.UI.WebControls.SqlDataSource

          '''<summary>
          '''ddlItemCd control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ddlItemCd As Global.System.Web.UI.WebControls.DropDownList

          '''<summary>
          '''SDAitem control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents SDAitem As Global.System.Web.UI.WebControls.SqlDataSource

          '''<summary>
          '''MastSetupSDA control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents MastSetupSDA As Global.System.Web.UI.WebControls.SqlDataSource

          '''<summary>
          '''Calendar1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Calendar1 As Global.System.Web.UI.WebControls.Calendar

          '''<summary>
          '''ImageButton4 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ImageButton4 As Global.System.Web.UI.WebControls.ImageButton

          '''<summary>
          '''txtStartDt control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtStartDt As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''btnfilter control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnfilter As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''User control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents User As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Version control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Version As Global.System.Web.UI.WebControls.Label
End Class
