'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MainPage

          '''<summary>
          '''form1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

          '''<summary>
          '''Image3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image

          '''<summary>
          '''ImportData control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ImportData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnImpMaterialMaster control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnImpMaterialMaster As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnImpProdOrder control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnImpProdOrder As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnImpProdOrderCom control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnImpProdOrderCom As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnVendBom control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnVendBom As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''MasterMaint control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents MasterMaint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label2 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnMStdUOM control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMStdUOM As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMShift control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMShift As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMProdCapa control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMProdCapa As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMLine control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMLine As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMProcess control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMProcess As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMStep control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMStep As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMEquip control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMEquip As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnStepEquip control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnStepEquip As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMTrace control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMTrace As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMBOM control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMBOM As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMReason control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMReason As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnWorkerReg control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnWorkerReg As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMCompCd control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMCompCd As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnPltCd control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnPltCd As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Operation control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Operation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnLotOp1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnLotOp1 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnLotOp2 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnLotOp2 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnPartMgmt control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnPartMgmt As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnPrintTag control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnPrintTag As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button15 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button15 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Report control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Report As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label4 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Button1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button2 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button3 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button4 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button4 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button5 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button5 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button6 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button6 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button7 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button7 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button8 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button8 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button9 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button9 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button10 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button10 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button14 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button14 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''ExportData control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ExportData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label5 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Button11 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button11 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button12 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button12 As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''Button13 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Button13 As Global.System.Web.UI.WebControls.Button
End Class
