'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MastReasonMaint01

          '''<summary>
          '''form1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

          '''<summary>
          '''formheader control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formheader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Image1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

          '''<summary>
          '''formtitle control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formtitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''frmtitle control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents frmtitle As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''formbody control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formbody As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnNew control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnNew As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''formcontent control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents formcontent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''gvContent control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents gvContent As Global.System.Web.UI.WebControls.GridView

          '''<summary>
          '''MastReasonSDA control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents MastReasonSDA As Global.System.Web.UI.WebControls.SqlDataSource

          '''<summary>
          '''ImageButton3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ImageButton3 As Global.System.Web.UI.WebControls.ImageButton

          '''<summary>
          '''User control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents User As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''DataEntryScr control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents DataEntryScr As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label3 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label4 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label5 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label8 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label9 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label6 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label7 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label10 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label11 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''txtRSNcd control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtRSNcd As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtRSNNM control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtRSNNM As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtRSNDiv control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtRSNDiv As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtRSNGrpCd control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtRSNGrpCd As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtSAPCostCntr control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtSAPCostCntr As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtSAPTrnCd control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtSAPTrnCd As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtSAPMovCd control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtSAPMovCd As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''txtRem control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents txtRem As Global.System.Web.UI.WebControls.TextBox

          '''<summary>
          '''btnSave control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnDelete control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnCancel control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''ImageButton1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

          '''<summary>
          '''ConfirmDelete control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ConfirmDelete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label2 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''Label12 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnConfirmDelete control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnConfirmDelete As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnCanceldelete control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnCanceldelete As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''ImageButton2 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton
End Class
