'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportDiv

          '''<summary>
          '''form1 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

          '''<summary>
          '''ReportFunc control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents ReportFunc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

          '''<summary>
          '''Label2 control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

          '''<summary>
          '''btnLineState control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnLineState As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnSerialOpen control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnSerialOpen As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnSerialHist control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnSerialHist As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnSerialSkip control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnSerialSkip As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnPartCons control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnPartCons As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnLotTrace control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnLotTrace As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnMotDock control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnMotDock As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnPartBal control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnPartBal As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnWorkerLog control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnWorkerLog As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnManuLotHistory control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnManuLotHistory As Global.System.Web.UI.WebControls.Button

          '''<summary>
          '''btnPartScrap control.
          '''</summary>
          '''<remarks>
          '''Auto-generated field.
          '''To modify move field declaration from designer file to code-behind file.
          '''</remarks>
          Protected WithEvents btnPartScrap As Global.System.Web.UI.WebControls.Button
End Class
