DROP INDEX [UK_MAST_STEP_EQUIPLINK_step_cd_equip_cd] ON [dbo].[MAST_STEP_EQUIPLINK]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UK_MAST_STEP_EQUIPLINK_step_cd_equip_cd] ON [dbo].[MAST_STEP_EQUIPLINK]
(
	[step_cd] ASC,
	[equip_cd] ASC,
	[line_id] ASC,
	[proc_flow_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


